# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56eda1a6a6ca7c3781d1c3d42375ba2a96e25291b81481a9c159c1df2a8881681029f803934ad2d5c90eaeb3448a5df9e9d947fdf978d0f4754923f183564423

test:
  secret_key_base: 983b3d559e2d5be68b7a1826c3aed6d03e32709b65ae6f9be9fb66db6b2034a533b407df76bcbda7b07a2151a43d26e6fdf51c6560f78e7711027f4765daddba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
